version: '3.5'

services:
  db:
    container_name: avito-task
    image:
      postgres:15.3-alpine
    environment:
      POSTGRES_DB: avito-task
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: